// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXhQBeUgO1h3rqBlGg9Dp6JkmL8nLXVw',
    appId: '1:839908546527:web:d395395dffc4ba5644166a',
    messagingSenderId: '839908546527',
    projectId: 'ai-powered-campus-radio',
    authDomain: 'ai-powered-campus-radio.firebaseapp.com',
    storageBucket: 'ai-powered-campus-radio.firebasestorage.app',
    measurementId: 'G-TRGJY1HQF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqsmQ089y2ZKYDZjs01emoBP1nriIQMQ',
    appId: '1:839908546527:android:281138e696ab734644166a',
    messagingSenderId: '839908546527',
    projectId: 'ai-powered-campus-radio',
    storageBucket: 'ai-powered-campus-radio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzr6gihpH283XZn-TjddPRsVyOO3C-6r4',
    appId: '1:839908546527:ios:553bd869be7584a544166a',
    messagingSenderId: '839908546527',
    projectId: 'ai-powered-campus-radio',
    storageBucket: 'ai-powered-campus-radio.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzr6gihpH283XZn-TjddPRsVyOO3C-6r4',
    appId: '1:839908546527:ios:553bd869be7584a544166a',
    messagingSenderId: '839908546527',
    projectId: 'ai-powered-campus-radio',
    storageBucket: 'ai-powered-campus-radio.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUXhQBeUgO1h3rqBlGg9Dp6JkmL8nLXVw',
    appId: '1:839908546527:web:fb81f3110270c80e44166a',
    messagingSenderId: '839908546527',
    projectId: 'ai-powered-campus-radio',
    authDomain: 'ai-powered-campus-radio.firebaseapp.com',
    storageBucket: 'ai-powered-campus-radio.firebasestorage.app',
    measurementId: 'G-36X1PYZC3P',
  );
}
