// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1d97tP173QsdgJtddC-MnXnrw456iUWQ',
    appId: '1:282752291468:web:73000ba23fdfa9e2ff21a9',
    messagingSenderId: '282752291468',
    projectId: 'cognitive-tuition-rlpe4q',
    authDomain: 'cognitive-tuition-rlpe4q.firebaseapp.com',
    storageBucket: 'cognitive-tuition-rlpe4q.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGkc3zsQlyrACXIxg1Dm-vjESauq2h_I',
    appId: '1:282752291468:android:b82d3a9d398ae543ff21a9',
    messagingSenderId: '282752291468',
    projectId: 'cognitive-tuition-rlpe4q',
    storageBucket: 'cognitive-tuition-rlpe4q.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5iewFQfpKI7gzJW8GoDHI1lg_eMwmww8',
    appId: '1:282752291468:ios:434f5565426e66acff21a9',
    messagingSenderId: '282752291468',
    projectId: 'cognitive-tuition-rlpe4q',
    storageBucket: 'cognitive-tuition-rlpe4q.firebasestorage.app',
    iosBundleId: 'com.mycompany.cognitivetuition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5iewFQfpKI7gzJW8GoDHI1lg_eMwmww8',
    appId: '1:282752291468:ios:434f5565426e66acff21a9',
    messagingSenderId: '282752291468',
    projectId: 'cognitive-tuition-rlpe4q',
    storageBucket: 'cognitive-tuition-rlpe4q.firebasestorage.app',
    iosBundleId: 'com.mycompany.cognitivetuition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1d97tP173QsdgJtddC-MnXnrw456iUWQ',
    appId: '1:282752291468:web:73000ba23fdfa9e2ff21a9',
    messagingSenderId: '282752291468',
    projectId: 'cognitive-tuition-rlpe4q',
    authDomain: 'cognitive-tuition-rlpe4q.firebaseapp.com',
    storageBucket: 'cognitive-tuition-rlpe4q.firebasestorage.app',
  );
}
