import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../../../services/firestore_service.dart';

class StudentNotificationsScreen extends StatefulWidget { const StudentNotificationsScreen({super.key}); @override State<StudentNotificationsScreen> createState() => _StudentNotificationsScreenState(); }
class _StudentNotificationsScreenState extends State<StudentNotificationsScreen> {
  var _unreadOnly = false; var _search = ''; final _read = <String>{};
  @override Widget build(BuildContext context) => Column(children: [
    Container(padding: const EdgeInsets.fromLTRB(20, 20, 20, 24), decoration: const BoxDecoration(gradient: LinearGradient(colors: [Color(0xFF312E81), Color(0xFF4F46E5)])), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Notifications', style: TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.w500)), const SizedBox(height: 14), TextField(onChanged: (v) => setState(() => _search = v), style: const TextStyle(color: Colors.white), decoration: const InputDecoration(prefixIcon: Icon(Icons.search, color: Color(0x99FFFFFF)), hintText: 'Search notifications…', hintStyle: TextStyle(color: Color(0x99FFFFFF)), filled: true, fillColor: Color(0x1FFFFFFF), border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(12)), borderSide: BorderSide(color: Color(0x33FFFFFF)))))])),
    Expanded(child: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(stream: FirestoreService.instance.collection('notifications'), builder: (_, snapshot) { if (snapshot.hasError) return const Center(child: Text('Notifications are unavailable right now.')); if (!snapshot.hasData) return const Center(child: CircularProgressIndicator()); final docs = snapshot.data!.docs.where((doc) { final d = doc.data(); final read = d['read'] == true || _read.contains(doc.id); return (!_unreadOnly || !read) && '${d['title'] ?? ''} ${d['message'] ?? d['body'] ?? ''}'.toLowerCase().contains(_search.toLowerCase()); }).toList(); final unread = snapshot.data!.docs.where((d) => d.data()['read'] != true && !_read.contains(d.id)).length; return Column(children: [Row(children: [Expanded(child: TextButton(onPressed: () => setState(() => _unreadOnly = false), child: Text('All', style: TextStyle(color: !_unreadOnly ? const Color(0xFF4F46E5) : null))),), Expanded(child: TextButton(onPressed: () => setState(() => _unreadOnly = true), child: Text('Unread ($unread)', style: TextStyle(color: _unreadOnly ? const Color(0xFF4F46E5) : null))),), if (unread > 0) TextButton(onPressed: () => setState(() => _read.addAll(snapshot.data!.docs.map((d) => d.id))), child: const Text('Mark all read'))]), Expanded(child: docs.isEmpty ? const Center(child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.notifications_none, size: 42, color: Color(0xFF9CA3AF)), SizedBox(height: 10), Text('All caught up!')])) : ListView.builder(itemCount: docs.length, itemBuilder: (_, i) { final doc = docs[i]; final d = doc.data(); final read = d['read'] == true || _read.contains(doc.id); final title = '${d['title'] ?? 'Notification'}'; final body = '${d['message'] ?? d['body'] ?? d['description'] ?? ''}'; final category = '${d['category'] ?? 'Campus'}'; return InkWell(onTap: () => setState(() => _read.add(doc.id)), child: Container(color: read ? null : const Color(0x0A4F46E5), padding: const EdgeInsets.all(16), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 44, height: 44, decoration: BoxDecoration(color: const Color(0xFFEEF2FF), borderRadius: BorderRadius.circular(14)), child: const Icon(Icons.notifications_outlined, color: Color(0xFF4F46E5))), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(category.toUpperCase(), style: const TextStyle(color: Color(0xFF4F46E5), fontSize: 10, fontWeight: FontWeight.w800)), const SizedBox(height: 3), Text(title, style: TextStyle(fontWeight: read ? FontWeight.w600 : FontWeight.w800)), const SizedBox(height: 3), Text(body, style: const TextStyle(color: Color(0xFF6B7280), fontSize: 12), maxLines: 2, overflow: TextOverflow.ellipsis)]), if (!read) const Padding(padding: EdgeInsets.only(left: 8, top: 5), child: CircleAvatar(radius: 3, backgroundColor: Color(0xFF4F46E5)))]))); }))]) ; }))
  ]);
}
