[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=3
board_build.partitions = huge_app.csv
lib_deps =
    esphome/ESP32-audioI2S@2.0.6
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
